DROP TABLE IF EXISTS `rule`;
CREATE TABLE `rule` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `name` varchar(64) DEFAULT NULL COMMENT '前台名称',
  `back_name` varchar(64) DEFAULT NULL COMMENT '后台名称',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '营销活动ID',
  `type` varchar(32) DEFAULT NULL COMMENT '规则类型',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '规则所属者ID',
  `owner_type` varchar(32) DEFAULT NULL COMMENT '规则所属者类型',
  `usage` varchar(255) DEFAULT NULL COMMENT '使用说明',
  `start_get_time` datetime COMMENT '领取开始时间',
  `end_get_time` datetime COMMENT '领取结束时间',
  `pic_url` varchar(255) DEFAULT NULL COMMENT '规则图片',
  `receive_type` varchar(32) COMMENT '领用类型',
  `max_num_limit` int(11) DEFAULT 0 COMMENT '最大发放/领用数量',
  `user_get_num` int(11) DEFAULT 0 COMMENT '用户已领用数量',
  `need_send` tinyint(1) DEFAULT 0 COMMENT '是否发放券',
  `need_receive` tinyint(1) DEFAULT 0 COMMENT '是否需要领取券',
  `can_transfer` tinyint(1) DEFAULT 0 COMMENT '是否支持转赠',
  `can_show` tinyint(1) DEFAULT 0 COMMENT '是否可见',
  `face_amount` decimal(15,6) COMMENT '面额',
  `status` varchar(32) COMMENT '规则状态',
  `start_from_receive` tinyint(1) DEFAULT 0 COMMENT '是否按领取日期计时',
  `start_use_time` datetime COMMENT '生效开始时间',
  `end_use_time` datetime COMMENT '生效结束时间',
  `days` int(11) DEFAULT 0 COMMENT '领取后有效天数',
  `max_get_times` int(11) DEFAULT 0 COMMENT '限制领取次数',
  `usage_notice` varchar(255) DEFAULT NULL COMMENT '使用须知',
  `discount_type` varchar(32) COMMENT '优惠类型',
  `discount_value` decimal(15,6) COMMENT '优惠数值',
  `condition_desc` varchar(255) DEFAULT NULL COMMENT '条件说明',
  `scope_desc` varchar(255) DEFAULT NULL COMMENT '作用域说明',
  `is_cycle` tinyint(1) DEFAULT 0 COMMENT '是否循环门槛',
  `opt_version` bigint(20) DEFAULT 0 COMMENT '乐观锁',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_rule_activity_id` (`activity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠规则';

DROP TABLE IF EXISTS `rule_condition`;
CREATE TABLE `rule_condition` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `name` varchar(64) DEFAULT NULL COMMENT '条件名称',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '营销活动ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '规则所属者ID',
  `owner_type` varchar(32) DEFAULT NULL COMMENT '规则所属者类型',
  `use_condition` varchar(32) DEFAULT NULL COMMENT '使用条件',
  `ladder_value`decimal(15,6)  DEFAULT 0 COMMENT '满减/满折的门槛数量',
  `ladder_max_value` decimal(15,6) DEFAULT 0 COMMENT '在循环模式下，门槛的封顶金额； 非循环模式忽略',
  `discount_type` varchar(32) DEFAULT NULL COMMENT '优惠计算类型,从Rule中冗余过来,同一个Rule不同的Condition的discountType必须一致',
  `discount_value` decimal(15,6)  DEFAULT 0 COMMENT '优惠数值,可能是金额，也可能是折扣',
  `gift_type` varchar(32) DEFAULT NULL COMMENT '赠品类型',
  `gift_method` varchar(32) DEFAULT NULL COMMENT '赠送类型',
  `gift_ids` varchar(255) DEFAULT NULL COMMENT '赠品ID列表,商品或者优惠券ID列表,ID之间英文逗号分隔',
  `desc` varchar(255) DEFAULT NULL COMMENT '满足条件说明',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_rule_condition_activity_id` (`activity_id`),
  KEY `idx_rule_condition_rule_id` (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规则使用条件';

DROP TABLE IF EXISTS `rule_scope`;
CREATE TABLE `rule_scope` (
   `id` bigint(20) NOT NULL COMMENT 'ID',
  `name` varchar(64) DEFAULT NULL COMMENT '条件名称',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '营销活动ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `rule_type` varchar(32) DEFAULT NULL COMMENT '规则类型',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '规则所属者ID',
  `owner_type` varchar(32) DEFAULT NULL COMMENT '规则所属者类型 平台 卖家',
  `scope_range` varchar(32) DEFAULT NULL COMMENT '作用域范围',
  `scope_type` varchar(32) DEFAULT NULL COMMENT '作用域条件',
  `scope_extra_value` decimal(15,6) DEFAULT 0 COMMENT '作用域值补充 在Scope=SKU时，填充折扣单价',
  `shop_code` varchar(128) COLLATE DEFAULT NULL COMMENT '店铺CODE',
  `item_id` bigint(20) DEFAULT NULL COMMENT '商品Id',
  `sale_sku_id` bigint(20) DEFAULT NULL COMMENT 'SKU ID',
  `scope_value` varchar(128) COLLATE DEFAULT NULL COMMENT '作用域值',
  `condition_ids` varchar(128) COLLATE DEFAULT NULL COMMENT '优惠使用条件ID列表,多个ID之间英文逗号分隔',
  `data_status` varchar(32) COLLATE DEFAULT NULL COMMENT '商品下架后，需要变更这个状态为DISABLED',
  `status` varchar(32) COLLATE DEFAULT NULL COMMENT '规则状态',
  `start_use_time` datetime DEFAULT NULL COMMENT '冗余规则的开始时间，方便查询用',
  `end_use_time` datetime DEFAULT NULL COMMENT '冗余规则的结束时间，方便查询用',
  `start_get_time` datetime DEFAULT NULL COMMENT '冗余规则的领用/发放开始时间',
  `end_get_time` datetime DEFAULT NULL COMMENT '冗余规则的领用/发放结束时间',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_rule_scope_activity_id` (`activity_id`),
  KEY `idx_rule_scope_rule_id` (`rule_id`),
  KEY `idx_rule_scope_item_id` (`item_id`),
  KEY `idx_rule_scope_sale_sku_id` (`sale_sku_id`),
  KEY `idx_rule_scope_start_use_time` (`start_use_time`),
  KEY `idx_rule_scope_end_use_time` (`end_use_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规则作用域';

DROP TABLE IF EXISTS `rule_statistics`;
CREATE TABLE `rule_statistics` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '活动ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `rule_total_num` int(11) DEFAULT NULL COMMENT '优惠券总数',
  `received_user_num` int(11) DEFAULT NULL COMMENT '领取人数',
  `received_num` int(11) DEFAULT NULL COMMENT '领取张数',
  `used_user_num` int(11) DEFAULT NULL COMMENT '已经使用人数',
  `used_num` int(11) DEFAULT NULL COMMENT '已经使用张数',
  `received_rate` decimal(15,6) DEFAULT NULL COMMENT '领取率',
  `used_rate` decimal(15,6) DEFAULT NULL COMMENT '使用率',
  `related_order_num` int(11) DEFAULT NULL COMMENT '关联订单',
  `related_order_amount` decimal(15,6) DEFAULT NULL COMMENT '支付金额',
  `related_item_num` int(11) DEFAULT NULL COMMENT '参与商品数',
  `opt_version` bigint(20) DEFAULT NULL COMMENT '乐观锁',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
 PRIMARY KEY (`id`),
  KEY `idx_rule_statistics_activity_id` (`activity_id`),
  KEY `idx_rule_statistics_rule_id` (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规则数据统计表';


DROP TABLE IF EXISTS `activity`;
CREATE TABLE `activity` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `name` varchar(128) DEFAULT NULL COMMENT '前台名称',
  `back_name` varchar(128) DEFAULT NULL COMMENT '活动后台名称',
  `theme` varchar(128) DEFAULT NULL COMMENT '活动主题，活动的Slogan',
  `desc` varchar(128) DEFAULT NULL COMMENT '活动描述',
  `start_time` datetime DEFAULT NULL COMMENT '活动开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '活动结束时间',
  `status` varchar(32) DEFAULT NULL COMMENT '活动状态',
  `owner_type` varchar(32) DEFAULT NULL COMMENT '活动所属者类型',
  `pic_url` varchar(512) DEFAULT NULL COMMENT '活动图片URL',
  `page_url` varchar(128) DEFAULT NULL COMMENT '活动页URL',
  `data_status` varchar(32) DEFAULT NULL COMMENT '数据状态',
  `code` varchar(128) DEFAULT NULL COMMENT '编码',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '活动所有者ID',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_activity_code` (`code`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销活动';

DROP TABLE IF EXISTS `activity_report`;
CREATE TABLE `activity_report` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '活动ID',
  `activity_scope` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '活动范围为SELLER_REPORT，则需要填写提报海报',
  `report_start_time` datetime DEFAULT NULL COMMENT '报名开始时间',
  `report_end_time` datetime DEFAULT NULL COMMENT '报名结束时间',
  `audit_start_time` datetime DEFAULT NULL COMMENT '审核开始时间',
  `audit_end_time` datetime DEFAULT NULL COMMENT '审核结束时间',
  `warm_up_start_time` datetime DEFAULT NULL COMMENT '预热开始时间',
  `warm_up_end_time` datetime DEFAULT NULL COMMENT '预热结束时间',
  `approve_status` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '审批状态',
  `seller_range` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商家范围',
  `item_range` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品范围',
  `activity_effect` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '活动力度',
  `item_stock_require` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品库存要求',
  `item_price_require` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商品货值要求',
  `max_item_num` bigint(20) DEFAULT NULL COMMENT '商品提报上限 99999代表不限',
  `act_detail` text COLLATE utf8mb4_bin COMMENT '活动详情的补充说明，支持图片等富文本',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_activity_report_activity_id` (`activity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='活动提报';

DROP TABLE IF EXISTS `activity_report_submit`;
CREATE TABLE `activity_report_submit` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_code` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '提报活动编码',
  `rule_type` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '规则类型',
  `shop_code` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '店铺code',
  `activity_scope` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '提报类型',
  `item_num` int(11) DEFAULT NULL COMMENT '提报商品数',
  `approve_status` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '审批状态',
  `audit_start_time` datetime DEFAULT NULL COMMENT '审核开始时间',
  `audit_end_time` datetime DEFAULT NULL COMMENT '审核结束时间',
  `code` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '营销活动ID',
  `activity_report_id` bigint(20) DEFAULT NULL COMMENT '活动提报ID',
  `seller_partner_id` bigint(20) DEFAULT NULL COMMENT '卖家ID',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_activity_report_submit_code` (`code`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='活动提报';

DROP TABLE IF EXISTS `activity_rule_item`;
CREATE TABLE `activity_rule_item` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_report_submit_id` bigint(20) DEFAULT NULL COMMENT '活动提报ID',
  `item_id` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `sale_sku_id` bigint(20) DEFAULT NULL COMMENT 'SKU ID',
  `remark` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '优惠规则ID',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='商家提报商品列表';

DROP TABLE IF EXISTS `coupon`;
CREATE TABLE `coupon` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '活动ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `rule_name` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '优惠名称',
  `discount_type` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '优惠计算类型 从rule中冗余过来，同一个Rule不同的Condition的discountType必须一致',
  `discount_value` decimal (15,6) DEFAULT NULL COMMENT '可能是金额，也可能是折扣',
  `buyer_partner_id` bigint(20) DEFAULT NULL COMMENT '买家id',
  `seller_partner_id` bigint(20) DEFAULT NULL COMMENT '卖家id',
  `coupon_owner_type` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属类型',
  `face_amount` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '面额',
  `usage` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '规则使用说明',
  `condition_desc` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '满足条件说明',
  `effective_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
  `effective_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
  `get_time` datetime DEFAULT NULL COMMENT '领取时间优惠券时间',
  `used_time` datetime DEFAULT NULL COMMENT '使用时间',
  `coupon_target` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '使用目标',
  `coupon_status` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '优惠券状态',
  `code` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `coupon_code` (`code`,`is_deleted`),
  KEY `idx_coupon_act_id` (`act_id`),
  KEY `idx_coupon_rule_id` (`rule_id`),
  KEY `idx_coupon_buyer_partner_id` (`buyer_partner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='优惠券实例';


DROP TABLE IF EXISTS `coupon_log`;
CREATE TABLE `coupon_log` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `coupon_code` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '优惠券编码',
  `buyer_id` bigint(20) DEFAULT NULL COMMENT '买家ID',
  `buyer_name` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '买家名称',
  `seller_id` bigint(20) DEFAULT NULL COMMENT '卖家id',
  `seller_name` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '卖家名称',
  `trade_order_id` bigint(20) DEFAULT NULL COMMENT '订单Id',
  `trade_order_amount` decimal(65,6) DEFAULT NULL COMMENT '订单金额',
  `coupon_log_type` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '优惠券日志状态',
  `has_roll_back` tinyint(1) DEFAULT NULL COMMENT '是否已回退',
  `used_time` datetime DEFAULT NULL COMMENT '使用时间',
  `coupon_id` bigint(20) DEFAULT NULL COMMENT '优惠券ID',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_coupon_log_rule_id` (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='优惠券实例使用日志';

DROP TABLE IF EXISTS `item_rule_statistics`;
CREATE TABLE `item_rule_statistics` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '活动ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `item_id` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `sku_id` bigint(20) DEFAULT NULL COMMENT 'SKU ID',
  `discount_unit_price` decimal(65,6) DEFAULT NULL COMMENT '折扣单价',
  `used_user_num` int(11) DEFAULT NULL COMMENT '已经使用人数',
  `used_num` int(11) DEFAULT NULL COMMENT '已经使用张数',
  `related_order_num` int(11) DEFAULT NULL COMMENT '关联订单',
  `related_order_amount` decimal (15,6) DEFAULT NULL COMMENT '支付金额',
  `opt_version` bigint(20) DEFAULT 0 COMMENT '乐观锁',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_item_rule_statistics_activity_id` (`activity_id`),
  KEY `idx_item_rule_statistics_rule_id` (`rule_id`),
  KEY `idx_item_rule_statistics_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='参与优惠商品数据统计表';

DROP TABLE IF EXISTS `buyer_rule_statistics`;
CREATE TABLE `buyer_rule_statistics` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `activity_id` bigint(20) DEFAULT NULL COMMENT '活动ID',
  `rule_id` bigint(20) DEFAULT NULL COMMENT '规则ID',
  `buyer_partner_id` bigint(20) DEFAULT NULL COMMENT '买家ID',
  `used_count` int(11) DEFAULT NULL COMMENT '使用次数',
  `opt_version` bigint(20) DEFAULT NULL COMMENT '乐观锁',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_buyer_rule_statistics_activity_id` (`activity_id`),
  KEY `idx_buyer_rule_statistics_rule_id` (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='在优惠中有限制使用次数';
